#!/usr/bin/env bash
# Usage: ./log.sh "what changed"  -> updates CONTEXT.md (open windows snapshot + capped log)
# Run from the repo, or set CONTEXT=/path/to/CONTEXT.md to track another project.
MAX_LOG=${MAX_LOG:-20}   # hard cap on log entries; oldest dropped
MAX_WIN=${MAX_WIN:-15}   # hard cap on windows listed
f=${CONTEXT:-CONTEXT.md}
old=$(sed -n '/^## Log/,$p' "$f" 2>/dev/null | grep '^- ')
{
  echo "# Context (auto-generated by log.sh, ~$((MAX_LOG+MAX_WIN+6)) lines max, read this first)"
  echo "## Open now ($(date '+%F %H:%M'), $(hostname))"
  # ponytail: wmctrl = X11 window titles only (active browser tab, not all tabs)
  wmctrl -l 2>/dev/null | cut -d' ' -f4- | cut -c1-80 | head -n "$MAX_WIN" | sed 's/^/- /'
  echo "## Log"
  { echo "$old"; [ -n "$1" ] && echo "- $(date '+%m-%d %H:%M') $1"; } | grep . | tail -n "$MAX_LOG"
} > "$f.tmp" && mv "$f.tmp" "$f"
